// Code generated by manual binding; DO NOT EDIT.
package contract

import (
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// Reference Imports to suppress errors if they are not otherwise used.
var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// VotingSystemABI is the input ABI used to generate the binding from.
const VotingSystemABI = `[{"inputs":[{"internalType":"uint256","name":"_electionId","type":"uint256"},{"internalType":"uint256","name":"_startTime","type":"uint256"},{"internalType":"uint256","name":"_endTime","type":"uint256"}],"name":"createElection","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_electionId","type":"uint256"},{"internalType":"uint256","name":"_candidateId","type":"uint256"},{"internalType":"uint256","name":"_voterId","type":"uint256"}],"name":"castVote","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_electionId","type":"uint256"},{"internalType":"uint256","name":"_candidateId","type":"uint256"}],"name":"getVotes","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_electionId","type":"uint256"},{"internalType":"uint256","name":"_voterId","type":"uint256"}],"name":"checkHasVoted","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"elections","outputs":[{"internalType":"uint256","name":"startTime","type":"uint256"},{"internalType":"uint256","name":"endTime","type":"uint256"},{"internalType":"bool","name":"exists","type":"bool"}],"stateMutability":"view","type":"function"}]`

// VotingSystem is an auto generated Go binding around an Ethereum contract.
type VotingSystem struct {
	VotingSystemCaller     // Read-only binding to the contract
	VotingSystemTransactor // Write-only binding to the contract
	VotingSystemFilterer   // Log filterer for contract events
}

// VotingSystemCaller is an auto generated read-only Go binding around an Ethereum contract.
type VotingSystemCaller struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// VotingSystemTransactor is an auto generated write-only Go binding around an Ethereum contract.
type VotingSystemTransactor struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// VotingSystemFilterer is an auto generated log filtering Go binding around an Ethereum contract.
type VotingSystemFilterer struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// NewVotingSystem creates a new instance of VotingSystem, bound to a specific deployed contract.
func NewVotingSystem(address common.Address, backend bind.ContractBackend) (*VotingSystem, error) {
	contract, err := bindVotingSystem(address, backend, backend, backend)
	if err != nil {
		return nil, err
	}
	return &VotingSystem{VotingSystemCaller: VotingSystemCaller{contract: contract}, VotingSystemTransactor: VotingSystemTransactor{contract: contract}, VotingSystemFilterer: VotingSystemFilterer{contract: contract}}, nil
}

// bindVotingSystem binds a generic wrapper to an already deployed contract.
func bindVotingSystem(address common.Address, caller bind.ContractCaller, transactor bind.ContractTransactor, filterer bind.ContractFilterer) (*bind.BoundContract, error) {
	parsed, err := abi.JSON(strings.NewReader(VotingSystemABI))
	if err != nil {
		return nil, err
	}
	return bind.NewBoundContract(address, parsed, caller, transactor, filterer), nil
}

// CreateElection is a paid mutator transaction binding the contract method "createElection"
func (_VotingSystem *VotingSystemTransactor) CreateElection(opts *bind.TransactOpts, _electionId *big.Int, _startTime *big.Int, _endTime *big.Int) (*types.Transaction, error) {
	return _VotingSystem.contract.Transact(opts, "createElection", _electionId, _startTime, _endTime)
}

// CastVote is a paid mutator transaction binding the contract method "castVote"
func (_VotingSystem *VotingSystemTransactor) CastVote(opts *bind.TransactOpts, _electionId *big.Int, _candidateId *big.Int, _voterId *big.Int) (*types.Transaction, error) {
	return _VotingSystem.contract.Transact(opts, "castVote", _electionId, _candidateId, _voterId)
}

// GetVotes is a free data retrieval call binding the contract method "getVotes"
func (_VotingSystem *VotingSystemCaller) GetVotes(opts *bind.CallOpts, _electionId *big.Int, _candidateId *big.Int) (*big.Int, error) {
	var out []interface{}
	err := _VotingSystem.contract.Call(opts, &out, "getVotes", _electionId, _candidateId)

	if err != nil {
		return *new(*big.Int), err
	}

	out0 := *abi.ConvertType(out[0], new(*big.Int)).(**big.Int)
	return out0, err
}
